version: '3.7'
services:
  db:
    image: 'postgres:latest'
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    # env_file:
    #   - ./env/postgres.env # you can also define env variables like this.
  rails_cmd:
    build: ./
    ports:
      - "4000:4000" #port mapping
    volumes:
      - ./:/docker/app
      
    depends_on:
      - db  # add all dependant container
    container_name: rails_cmd
volumes:
  postgres: # named volume