version: '3.7'
services:
  db:
    image: 'postgres:latest'
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    # env_file:
    #   - ./env/postgres.env # you can also define env variables like this.
  rails_cmd:
    build: /data/coolify/applications/ksc08cs/
    ports:
      - "3000:3000" #port mapping
    volumes:
      - ./:/docker/app
      
    depends_on:
      - db  # add all dependant container

volumes:
  postgres: # named volume